site_name: Thesis Magister Física Médica UC Andrés Aracena

nav:
    - Inicio: 'index.md'
    - 'Funciones':
        - 'Funcion atributo img': '00_00_funcion_atributos.md'
        - 'Función order slice': '00_01_funcion_orderslice.md'
        
theme: readthedocs